using System;

namespace UnityExpansion
{
    /// <summary>
    /// Converts field to autogenerated unique persistent ID.
    /// ID will be generated automatically in editor mode using reflection.
    /// </summary>
    [AttributeUsage(AttributeTargets.Field)]
    public class UniquePersistenID : Attribute
    {
    }
}